# Site settings
title: The Code Deli
email: contact@thecodedeli.com
description: > # this means to ignore newlines until "baseurl:"
  The Code Deli is an awesome web development agency. We specialize in
  Ruby on Rails, Shopify, WordPress, and Graphic Design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.thecodedeli.com" # the base hostname & protocol for your site
github_username: TheCodeDeli

# Build settings
markdown: redcarpet
highlighter: pygments

redcarpet:
  extensions:
    - autolink

gems:
  - jekyll-sitemap
